
client_id = "5aaded2899d449156c5deb413cb205f3"
name = "form-app-designdirect"
application_url = "https://researchers-tracked-supporting-recommendation.trycloudflare.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "write_products,write_app_proxy,write_metaobjects,read_metaobjects,read_metaobject_definitions,write_metaobject_definitions,write_files"

[app_proxy]
url = "/configurator"
prefix = "apps"
subpath = "configurator"


[auth]
redirect_urls = [
    "https://researchers-tracked-supporting-recommendation.trycloudflare.com/api/auth",
]
