# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eacb6fcc1419111e0841a58a62cc09dc"
name = "form-app-designdirect"
application_url = "https://example.com"
embedded = true
apiKey = "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"
[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions,read_metaobjects,write_app_proxy,write_files,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = ["https://example.com/api/auth"]
